# Generated by Django 6.0.5 on 2026-06-01 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaRentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('transaction_type', models.CharField(default='Pay Bill', max_length=20)),
                ('transaction_time', models.DateTimeField()),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('matched_by', models.CharField(choices=[('phone', 'Phone Number'), ('account_ref', 'Account Reference'), ('amount', 'Amount Match'), ('manual', 'Manual Match'), ('unmatched', 'Unmatched')], default='unmatched', max_length=20)),
                ('tenant_sms_sent', models.BooleanField(default=False)),
                ('tenant_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_email_sent', models.BooleanField(default=False)),
                ('tenant_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('agent_sms_sent', models.BooleanField(default=False)),
                ('agent_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('agent_email_sent', models.BooleanField(default=False)),
                ('agent_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('lease_rent_updated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agent')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='properties.lease')),
                ('linked_rent_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_source', to='properties.rentpayment')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='properties.tenant')),
            ],
            options={
                'verbose_name': 'M-Pesa Rent Payment',
                'verbose_name_plural': 'M-Pesa Rent Payments',
                'ordering': ['-transaction_time'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('tenant', 'Tenant'), ('agent', 'Agent/Landlord')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('recipient', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('provider_response', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_logs', to='payments.mpesarentpayment')),
            ],
        ),
    ]
