# Generated by Django 5.1.4 on 2026-06-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Property Analytics',
                'verbose_name_plural': 'Property Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('properties.property',),
        ),
    ]
