# Generated by Django 5.2.5 on 2026-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('land', 'Land')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'Sold'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-date_listed'],
            },
        ),
    ]
