# Generated by Django 5.2.5 on 2026-04-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.CreateModel(
            name='PropertyAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Property Analytics',
                'verbose_name_plural': 'Property Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('properties.property',),
        ),
    ]
