# Generated by Django 4.2.23 on 2025-08-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
