# Generated by Django 4.2.23 on 2025-08-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(default='Unkown', max_length=100),
        ),
    ]
