# Generated by Django 4.2.23 on 2025-07-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerlead',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TSH', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ZAR', 'South African Rand'), ('TZS', 'Tanzanian Shilling'), ('KWD', 'Kuwaiti Dinar'), ('AED', 'United Arab Emirates Dirham'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('SGD', 'Singapore Dollar'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('PHP', 'Philippine Peso'), ('IDR', 'Indonesian Rupiah')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lease',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TSH', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ZAR', 'South African Rand'), ('TZS', 'Tanzanian Shilling'), ('KWD', 'Kuwaiti Dinar'), ('AED', 'United Arab Emirates Dirham'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('SGD', 'Singapore Dollar'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('PHP', 'Philippine Peso'), ('IDR', 'Indonesian Rupiah')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TSH', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ZAR', 'South African Rand'), ('TZS', 'Tanzanian Shilling'), ('KWD', 'Kuwaiti Dinar'), ('AED', 'United Arab Emirates Dirham'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('SGD', 'Singapore Dollar'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('PHP', 'Philippine Peso'), ('IDR', 'Indonesian Rupiah')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TSH', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ZAR', 'South African Rand'), ('TZS', 'Tanzanian Shilling'), ('KWD', 'Kuwaiti Dinar'), ('AED', 'United Arab Emirates Dirham'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('SGD', 'Singapore Dollar'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('PHP', 'Philippine Peso'), ('IDR', 'Indonesian Rupiah')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TSH', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ZAR', 'South African Rand'), ('TZS', 'Tanzanian Shilling'), ('KWD', 'Kuwaiti Dinar'), ('AED', 'United Arab Emirates Dirham'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('SGD', 'Singapore Dollar'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('PHP', 'Philippine Peso'), ('IDR', 'Indonesian Rupiah')], default=0, max_length=3),
        ),
    ]
