# Generated by Django 5.2.5 on 2025-08-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('resort', 'Resort'), ('land', 'Land'), ('office', 'Office'), ('warehouse', 'Warehouse'), ('retail', 'Retail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('resort', 'Resort'), ('land', 'Land'), ('office', 'Office'), ('warehouse', 'Warehouse'), ('retail', 'Retail')], default='house', max_length=20),
        ),
    ]
