# Generated by Django 5.1.4 on 2026-06-18 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agency_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('independent', 'Independent Agent'), ('agency', 'Agency Representative'), ('landlord_agent', 'Landlord & Agent'), ('tenant_agent', 'Tenant & Agent')], default='independent', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='business_certificate',
            field=models.FileField(blank=True, null=True, upload_to='agents/documents/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='business_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Registration Number'),
        ),
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='agents/documents/', verbose_name='National ID/Passport'),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='license_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Real Estate License Number'),
        ),
        migrations.AddField(
            model_name='agent',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='properties_managed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
