# Generated by Django 5.1.6 on 2025-04-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_lease_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('size_in_hectares', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('square_footage', models.FloatField(help_text='Total area in square feet')),
                ('retail_type', models.CharField(choices=[('store', 'Store'), ('shop', 'Shop')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='has_boat_rental',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='has_snorkeling_center',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='has_yacht_rental',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='has_restaurant_loyalty_program',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='has_restaurant_software',
        ),
        migrations.AddField(
            model_name='house',
            name='square_footage',
            field=models.FloatField(default=0, help_text='Size in square meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default=1000, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(default=0, help_text='Type of cuisine served', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('hotel', 'Hotel'), ('apartment', 'Apartment'), ('restaurant', 'Restaurant'), ('beach_land', 'Beach Land'), ('office', 'Office'), ('resort', 'Resort'), ('land', 'Land'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural'), ('vacation_home', 'Vacation Home'), ('retail_space', 'Retail Space'), ('warehouse', 'Warehouse'), ('mixed_use', 'Mixed Use'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Agricultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField()),
                ('crop_type', models.CharField(max_length=100)),
                ('has_irrigation_system', models.BooleanField(default=False)),
                ('has_fencing', models.BooleanField(default=False)),
                ('has_access_road', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField()),
                ('zoning_type', models.CharField(max_length=100)),
                ('has_parking_space', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_water_supply', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Industrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industrial_type', models.CharField(help_text='Type of industrial property', max_length=100)),
                ('square_footage', models.FloatField(help_text='Total area in square meters')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industrial', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='MixedUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('has_parking_space', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_water_supply', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mixed_use', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('has_parking_space', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_water_supply', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bedrooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_parking_space', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_home', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField()),
                ('has_loading_dock', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_water_supply', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='properties.property')),
            ],
        ),
    ]
