# Generated by Django 5.1.6 on 2025-04-09 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_agricultural_image_apartment_image_beachland_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='name',
        ),
        migrations.AddField(
            model_name='land',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retail',
            name='location',
            field=models.CharField(choices=[('mombasa', 'Mombasa')], max_length=255),
        ),
    ]
