# Generated by Django 5.1.6 on 2025-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_property_owner_remove_tenant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='verification_code_expiry',
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('land', 'Land'), ('office', 'Office'), ('warehouse', 'Warehouse'), ('retail', 'Retail')], max_length=20),
        ),
    ]
