# Generated by Django 5.1.6 on 2025-04-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_property_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.agent'),
        ),
    ]
