# Generated by Django 5.1.6 on 2025-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_tenant_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='payment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20),
        ),
    ]
