# Generated by Django 5.1.6 on 2025-04-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_rentpayment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='lease_document',
        ),
        migrations.AlterField(
            model_name='lease',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('mpesa', 'M-Pesa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('mpesa', 'M-Pesa')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('mpesa', 'M-Pesa')], max_length=100),
        ),
    ]
