# Generated by Django 5.1.6 on 2025-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='property_name',
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(blank=True, help_text="Type of lease ('gross', 'net', 'modified_gross', 'triple_net')", max_length=50, null=True),
        ),
    ]
