# Generated by Django 5.1.6 on 2025-05-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_rename_name_property_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission amount earned by the agent for this tenant', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='stamp_duty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Stamp duty for this lease', max_digits=10, null=True),
        ),
    ]
