# Generated by Django 5.1.6 on 2025-05-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_agent_commission_amount_agent_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='properties.agent'),
        ),
    ]
