# Generated by Django 5.1.6 on 2025-05-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_lease_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.agent'),
        ),
    ]
