# Generated by Django 5.1.6 on 2025-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_buyerlead_contactmessage_sellerlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlead',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='location',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('shop', 'Shop'), ('office', 'Office')], default='house', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyerlead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyerlead',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buyerlead',
            name='preferred_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='property_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
