# Generated by Django 5.1.6 on 2025-06-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_blogpost_alter_sellerlead_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='featured_image',
            new_name='image',
        ),
    ]
