# Generated by Django 5.1.6 on 2025-06-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_rename_featured_image_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('transanction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('Agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.agent')),
            ],
        ),
    ]
