# Generated by Django 5.1.6 on 2025-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_agentsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='subscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
