# Generated by Django 5.1.6 on 2025-06-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_agent_is_premium_agent_subscribed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentsubscription',
            old_name='Agent',
            new_name='agent',
        ),
    ]
