"""
Django settings for property_mgmt project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
from dotenv import load_dotenv
from decouple import config

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Load environment variables
load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tj6t^#(83bs9=k$2on9_jvr0!u0z4*rm4ku(oit+-skg2r9l2@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DJANGO_SETTINGS_MODULE = "property_mgmt.settings"

# openai
from dotenv import load_dotenv
import os

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_q',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',
    'django_extensions',
    'widget_tweaks',
   

    # Custom apps
     
    'frontend',  # Frontend App for the Property Management System
    'properties',  # Property Management App
    'transactions', # Transaction Management App
    'reports',  # Reporting App
    'testimonial',  # Testimonials App
    'subscriptions',  # Subscription Management App
    
    # Third-party apps
    'rest_framework',  # Django REST Framework
    'channels',
    'chat',
    'rest_framework_simplejwt', # JWT Authentication
      
    
]

Q_CLUSTER = {
    'name': 'ZiaQ',
    'workers': 4,
    'timeout': 60,
    'retry': 90,
    'queue_limit': 50,
    'orm': 'default',
}

JAZZMIN_SETTINGS = {
    "site_title": "Zia Property Admin",
    "site_header": "Zia Property Dashboard",
    "site_brand": "Zia Properties Ltd",
    "welcome_sign": "Welcome to Zia Admin",
    "copyright": "Zia Properties Ltd",
    "search_model": ["properties.Property"],  # optional
    "order_with_respect_to": ["properties", "accounts"],

    # -*- coding: utf-8 -*-

    "icons": {
        # 🔐 Built-in apps
        "auth.Group": "fas fa-user-shield",
        "auth.User": "fas fa-user",

        # 📧 Email (django-allauth)
        "account.EmailAddress": "fas fa-envelope",
        "account.EmailConfirmation": "fas fa-envelope-open-text",

        # 🌐 Social Auth
        "socialaccount.SocialApp": "fas fa-cogs",
        "socialaccount.SocialAccount": "fab fa-facebook-square",
        "socialaccount.SocialToken": "fas fa-key",

        #AI chat
        "chat.ChatMessage": "fas fa-comments",

        # 🏘️ Property System (properties app)
        "properties.Agent": "fas fa-user-tie",
        "properties.AgentSubscription": "fas fa-id-badge",
        "properties.Property": "fas fa-home",
        "properties.PropertyImage": "fas fa-image",
        "properties.BuyerLead": "fas fa-user-plus",
        "properties.SellerLead": "fas fa-user-minus",
        "properties.BlogPost": "fas fa-blog",
        "properties.Tenant": "fas fa-users",
        "properties.Lease": "fas fa-file-contract",
        "properties.RentPayment": "fas fa-money-check-alt",
        "properties.MaintenanceRequest": "fas fa-tools",
        "properties.Inspection": "fas fa-search",
        "properties.Payment": "fas fa-money-bill-wave",
        "properties.ContactMessage": "fas fa-envelope-open",

        # 📈 Reports
        "reports.IncomeReport": "fas fa-chart-line",

        "subscriptions.PremiumSubscription": "fas fa-crown",  # 👑 Crown icon for premium
        "subscriptions.MpesaAuditLog": "fas fa-file-invoice-dollar",  # 💵 Payment log icon

        # 💳 Transactions
        "transactions.Transaction": "fas fa-credit-card",
        "transactions.MpesaTransaction": "fas fa-mobile-alt",

        # 💬 Testimonials
        "testimonial.Testimonial": "fas fa-comment-dots",

                # Django Q core models
        "django_q.Failure": "fas fa-times-circle",         # ❌ Failed tasks
        "django_q.Task": "fas fa-hourglass-alt",          #  Queued / running tasks
        "django_q.Schedule": "fas fa-calendar-alt  ",        # 📅 Scheduled tasks
        "django_q.Success": "fas fa-check-circle",         # ✅ Successful tasks

        # Bonus suggestion for overall tasks:
        "django_q.QueuedTask": "fas fa-tasks",             # 🧾 QueuedTask (if you define it)

    },

    "custom_links": {
    "django_q": [{
        "name": "View Q Cluster Logs",
        "url": "/admin/django_q/task/",
        "icon": "fas fa-tasks",
        "permissions": ["django_q.view_task"]
    }],
},

}


JAZZMIN_UI_TWEAKS = {
    "css": "frontend/custom_dark.css"
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]


# Optional: collect all static files into one folder (e.g. for deployment)
STATICFILES_DIRS = [
    BASE_DIR / 'property_mgmt_backend' / 'static',
    BASE_DIR / 'frontend',  # Additional static files directory
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Authentication settings for DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    
        'rest_framework.authentication.SessionAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Middleware configuration

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',

    # Custom middleware
    "subscriptions.middleware.PremiumRequiredMiddleware",
]

premium_paths = [
    "/premium/",
    "/properties/add/",
]

ROOT_URLCONF = 'property_mgmt.urls'

import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR/'frontend'/'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'property_mgmt.wsgi.application'

ASGI_APPLICATION = "property_mgmt.asgi.application"

# Redis for real-time communication
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # make sure Redis is running
        },
    },
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'property_management_system',
        'USER': 'gwiternz',
        'PASSWORD': '@#93Gwiternz29#@',
        'HOST': '127.0.0.1', # <-- NOT 'localhost'
        'PORT': '5432',
    }
}

# Mpesa Daraja API Settings
MPESA_CONSUMER_KEY = "jG8krQFuzcdYn9EFwwlvMdyC9nLxufKTzJOnHAUYKrFoPUer"
MPESA_CONSUMER_SECRET = "sNIS1DYt5jl1P1tdsD3oY1kle10nsgGCROyG5aFy8GNIkU28elfZgmqCXX2iMeoP"
MPESA_BASE_URL = "https://sandbox.safaricom.co.ke"
MPESA_SHORTCODE = "174379"
MPESA_PASSKEY = "<your-lipa-na-mpesa-passkey>"  # Still required

# My Ngrok/Public callback base
MPESA_CALLBACK_URL = 'https://baec-129-222-187-16.ngrok-free.app'


# Email
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"

DEFAULT_FROM_EMAIL = 'noreply@zia-properties.com'


CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app"
]

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ALLOWED_HOSTS = ['*']

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'dashboard/login/'
  
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/'


# Removed invalid pytest configuration from settings.py.