"""
Django settings for property_mgmt project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

"""
Django settings for property_mgmt project.
Production-ready for Render deployment.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

try:
    import dj_database_url
except ImportError:
    dj_database_url = None  # noqa: F401

BASE_DIR = Path(__file__).resolve().parent.parent

# Load local .env for development only
if os.getenv('RENDER') is None:
    load_dotenv(BASE_DIR / '.env', override=True)

# =============================================================================
# SECURITY
# =============================================================================

SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is required")

DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'zia-property.onrender.com',
    'ziapropertyagency.com',
    'www.ziapropertyagency.com',
]

# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    'jazzmin',
    'django_q',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',
    'django_extensions',
    'widget_tweaks',

    # Custom apps
    'analytics',
    'frontend',
    'properties',
    'transactions',
    'reports',
    'testimonial',
    'subscriptions',
    'payments',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
]

SITE_ID = 1

# =============================================================================
# DJANGO-Q (Background Tasks — Database-backed, no Redis needed)
# =============================================================================

Q_CLUSTER = {
    'name': 'ZiaQ',
    'workers': 2,
    'timeout': 60,
    'retry': 90,
    'queue_limit': 50,
    'orm': 'default',
}

# =============================================================================
# JAZZMIN ADMIN
# =============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "Zia Property Admin",
    "site_header": "Zia Property Dashboard",
    "site_brand": "Zia Properties Ltd",
    "welcome_sign": "Welcome to Zia Admin",
    "copyright": "Zia Properties Ltd",
    "search_model": ["properties.Property"],
    "order_with_respect_to": ["properties", "accounts"],
    "icons": {
        "auth.Group": "fas fa-user-shield",
        "auth.User": "fas fa-user",
        "account.EmailAddress": "fas fa-envelope",
        "account.EmailConfirmation": "fas fa-envelope-open-text",
        "socialaccount.SocialApp": "fas fa-cogs",
        "socialaccount.SocialAccount": "fab fa-facebook-square",
        "socialaccount.SocialToken": "fas fa-key",
        "properties.Agent": "fas fa-user-tie",
        "properties.AgentSubscription": "fas fa-id-badge",
        "properties.Property": "fas fa-home",
        "properties.PropertyImage": "fas fa-image",
        "properties.BuyerLead": "fas fa-user-plus",
        "properties.SellerLead": "fas fa-user-minus",
        "properties.BlogPost": "fas fa-blog",
        "properties.Tenant": "fas fa-users",
        "properties.Lease": "fas fa-file-contract",
        "properties.RentPayment": "fas fa-money-check-alt",
        "properties.MaintenanceRequest": "fas fa-tools",
        "properties.Inspection": "fas fa-search",
        "properties.Payment": "fas fa-money-bill-wave",
        "properties.ContactMessage": "fas fa-envelope-open",
        "reports.IncomeReport": "fas fa-chart-line",
        "subscriptions.PremiumSubscription": "fas fa-crown",
        "subscriptions.MpesaAuditLog": "fas fa-file-invoice-dollar",
        "transactions.Transaction": "fas fa-credit-card",
        "transactions.MpesaTransaction": "fas fa-mobile-alt",
        "testimonial.Testimonial": "fas fa-comment-dots",
        "django_q.Failure": "fas fa-times-circle",
        "django_q.Task": "fas fa-hourglass-alt",
        "django_q.Schedule": "fas fa-calendar-alt",
        "django_q.Success": "fas fa-check-circle",
    },
    "custom_links": {
        "django_q": [{
            "name": "View Q Cluster Logs",
            "url": "/admin/django_q/task/",
            "icon": "fas fa-tasks",
            "permissions": ["django_q.view_task"]
        }],
    },
}

JAZZMIN_UI_TWEAKS = {
    "css": "frontend/custom_dark.css"
}

# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / 'property_mgmt_backend' / 'static',
    BASE_DIR / 'frontend',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# =============================================================================
# MEDIA FILES (Local — WARNING: Won't persist on Render without S3/R2)
# =============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# TODO: Configure Cloudflare R2 or AWS S3 for persistent file storage
# When ready, uncomment and configure django-storages:
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
# AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
# AWS_S3_ENDPOINT_URL = os.getenv('R2_ENDPOINT_URL')  # e.g., https://<account>.r2.cloudflarestorage.com
# AWS_S3_REGION_NAME = 'auto'

# =============================================================================
# AUTHENTICATION
# =============================================================================

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'subscriptions.middleware.PremiumRequiredMiddleware',
]

premium_paths = [
    "/premium/",
    "/properties/add/",
]

# =============================================================================
# URLS & TEMPLATES
# =============================================================================

ROOT_URLCONF = 'property_mgmt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'property_mgmt.wsgi.application'

# =============================================================================
# ASGI / CHANNELS (Disabled — no WebSocket in production)
# =============================================================================

# ASGI_APPLICATION = "property_mgmt.asgi.application"
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379')],
#         },
#     },
# }

# =============================================================================
# DATABASE
# =============================================================================

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', 'sqlite:///db.sqlite3'),
        conn_max_age=600,
    )
}

# =============================================================================
# M-PESA SETTINGS
# =============================================================================

MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY")
MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET")
MPESA_BASE_URL = os.getenv("MPESA_BASE_URL", "https://sandbox.safaricom.co.ke")
MPESA_SHORTCODE = os.getenv("MPESA_SHORTCODE")
MPESA_PASSKEY = os.getenv("MPESA_PASSKEY")
MPESA_SECURITY_CREDENTIAL = os.getenv("MPESA_SECURITY_CREDENTIAL")
MPESA_CALLBACK_URL = os.getenv("MPESA_CALLBACK_URL")

# =============================================================================
# EMAIL
# =============================================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@zia-properties.com")

# =============================================================================
# AFRICA'S TALKING (Placeholder — not integrated yet)
# =============================================================================

AFRICASTALKING_USERNAME = os.getenv("AFRICASTALKING_USERNAME", "")
AFRICASTALKING_API_KEY = os.getenv("AFRICASTALKING_API_KEY", "")

# =============================================================================
# OPENAI (Placeholder — not integrated yet)
# =============================================================================

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_WORKFLOW_ID = os.getenv("OPENAI_WORKFLOW_ID", "")

# =============================================================================
# SECURITY HEADERS
# =============================================================================

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://ziapropertyagency.com",
    "https://www.ziapropertyagency.com",
]

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'dashboard/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/'