# Generated by Django 5.2.3 on 2025-06-29 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Payment', 'Payment'), ('Charge', 'Charge'), ('Refund', 'Refund')], default='Payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TSH', 'Tsh'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ZAR', 'South African Rand'), ('TZS', 'Tanzanian Shilling'), ('KWD', 'Kuwaiti Dinar'), ('AED', 'United Arab Emirates Dirham'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('SGD', 'Singapore Dollar'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('PHP', 'Philippine Peso'), ('IDR', 'Indonesian Rupiah'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('ARS', 'Argentine Peso'), ('CLP', 'Chilean Peso'), ('COP', 'Colombian Peso'), ('PEN', 'Peruvian Sol')], default='KES', max_length=3)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.agent')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
