# Generated by Django 5.1.6 on 2025-04-26 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_lease_image_remove_tenant_verification_code_and_more'),
        ('transactions', '0006_alter_transaction_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TSH', 'Tsh'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ZAR', 'South African Rand'), ('TZS', 'Tanzanian Shilling'), ('KWD', 'Kuwaiti Dinar'), ('AED', 'United Arab Emirates Dirham'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('SGD', 'Singapore Dollar'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('PHP', 'Philippine Peso'), ('IDR', 'Indonesian Rupiah'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('ARS', 'Argentine Peso'), ('CLP', 'Chilean Peso'), ('COP', 'Colombian Peso'), ('PEN', 'Peruvian Sol')], default='KES', max_length=3),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.tenant'),
        ),
    ]
