# Generated by Django 5.1.6 on 2025-04-26 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_lease_image_remove_tenant_verification_code_and_more'),
        ('transactions', '0007_alter_transaction_currency_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.tenant'),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
