# Generated by Django 5.1.6 on 2025-04-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_remove_lease_lease_document_and_more'),
        ('transactions', '0008_alter_transaction_tenant_delete_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.agent'),
        ),
    ]
