# Generated by Django 5.1.6 on 2025-05-09 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='incomereport',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='incomereport',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='incomereport',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='number_of_payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomereport',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
