# Generated by Django 5.2.5 on 2025-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
