# Generated by Django 5.2.5 on 2025-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_premiumsubscription_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='payment_gateway',
            field=models.CharField(default='MPESA', max_length=50),
        ),
    ]
