# Generated by Django 5.2.5 on 2026-03-14 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_premiumsubscription_payment_gateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesaauditlog',
            options={'verbose_name': 'M-Pesa Audit Log'},
        ),
        migrations.AlterModelOptions(
            name='premiumsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Premium Subscription'},
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly (30 Days)'), ('annual', 'Annual (365 Days)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
