# Generated by Django 6.0.6 on 2026-06-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_mpesaauditlog_options_and_more'),
    ]

    operations = [
    ]
