# Generated by Django 6.0.6 on 2026-06-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20260619_1145'),
        ('subscriptions', '0005_auto_20260619_1146'),
    ]

    operations = [
    ]
