name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:latest
        env:
          # These must match what the 'Run Tests' env uses
          POSTGRES_DB: postgres
          POSTGRES_USER: gwiternz
          POSTGRES_PASSWORD: "@#93Gwiternz29#@"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-django
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: property_mgmt.settings
        PYTHONPATH: .
        DB_NAME: postgres
        DB_USER: gwiternz
        DB_PASSWORD: "@#93Gwiternz29#@"
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      run: |
        # Using 'python -m pytest' ensures it uses the venv-installed plugins
        python -m pytest
